Update patch set 1
Patch Set 1:

Opps. Omitted the description which was:- Probably not best to merge this patch as I'm not sure what the implications will be for the Lineage automated building systems.

However, on my aged Linux box with a Intel Core 2 Duo E8400 running Ubuntu 16.04 I was getting these errors when using brunch:-

ERROR: Dex2oat failed to compile a boot image. It is likely that the boot classpath is inconsistent. Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS=--runtime-arg -verbose:verifier to see verification errors

This fixed it.

Patch-set: 1
Reviewer: Gareth Kitchen <18903@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>